export const BASE_URL = "https://disease.sh";
export const COUNTRIES = "COUNTRIES";
export const HISTORY = "HISTORY";
export const WORLDWIDE = "WORLDWIDE";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_WORLDWIDE_DETAILS = "GET_WORLDWIDE_DETAILS";
export const GET_COUNTRIE_DETAILS = "GET_COUNTRIE_DETAILS";
export const GET_WORLDWIDE_HISTORY_DATA = "GET_WORLDWIDE_HISTORY_DATA";
